-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Insurance cost drivers & motor claim frequency - SQL pipeline (Databricks SQL)
-- MAGIC **Status: executed on Databricks** (serverless SQL warehouse). Generated by `scripts/build_databricks.py` from `sql/`.
-- MAGIC
-- MAGIC 1. Upload `insurance.csv`, `freMTPL2freq.csv`, `freMTPL2sev.csv` to the Unity Catalog volume `/Volumes/workspace/da_learn_18/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
-- MAGIC 3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_18;
USE CATALOG workspace;
USE SCHEMA da_learn_18;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`), casting happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_medical AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_18/raw/insurance.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_motor_policy AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_18/raw/freMTPL2freq.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_motor_claim AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_18/raw/freMTPL2sev.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; runs on DuckDB via 00_duckdb_compat.sql shims)

CREATE OR REPLACE TABLE cln_medical AS
WITH typed AS (
  SELECT
    TRY_CAST(trim(age) AS INT)                                         AS age,
    CASE WHEN lower(trim(sex)) IN ('male', 'm') THEN 'male'
         WHEN lower(trim(sex)) IN ('female', 'f') THEN 'female'
         ELSE NULL END                                                 AS sex,
    TRY_CAST(trim(bmi) AS DOUBLE)                                      AS bmi,
    TRY_CAST(trim(children) AS INT)                                    AS children,
    CASE WHEN lower(trim(smoker)) IN ('yes', 'y', '1', 'true') THEN 1
         WHEN lower(trim(smoker)) IN ('no', 'n', '0', 'false') THEN 0
         ELSE NULL END                                                 AS smoker_flag,
    lower(trim(region))                                                AS region,
    TRY_CAST(trim(charges) AS DOUBLE)                                  AS charges
  FROM stg_medical
), dedup AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY age, sex, bmi, children, smoker_flag, region, charges
                               ORDER BY age) AS rn
  FROM typed
), valid AS (
  SELECT * FROM dedup
  WHERE rn = 1 AND age BETWEEN 18 AND 100 AND sex IS NOT NULL AND smoker_flag IS NOT NULL
    AND region IS NOT NULL AND charges > 0 AND bmi BETWEEN 10 AND 80 AND children >= 0
), bounds AS (
  SELECT percentile_approx(charges, 0.25) AS q1, percentile_approx(charges, 0.75) AS q3,
         percentile_approx(charges, 0.99) AS p99
  FROM valid
)
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY v.age, v.sex, v.bmi, v.children, v.smoker_flag, v.region, v.charges) AS INT) AS member_id,
  v.age, v.sex, v.bmi, v.children, v.smoker_flag,
  CASE WHEN v.smoker_flag = 1 THEN 'smoker' ELSE 'non-smoker' END     AS smoker_status,
  v.region,
  ROUND(v.charges, 2)                                                 AS charges,
  CASE WHEN v.age < 25 THEN '01: 18-24' WHEN v.age < 35 THEN '02: 25-34' WHEN v.age < 45 THEN '03: 35-44'
       WHEN v.age < 55 THEN '04: 45-54' ELSE '05: 55-64' END          AS age_band,
  CASE WHEN v.bmi < 18.5 THEN '1: Underweight' WHEN v.bmi < 25 THEN '2: Normal'
       WHEN v.bmi < 30 THEN '3: Overweight' ELSE '4: Obese' END       AS bmi_category,
  CASE WHEN v.bmi >= 30 THEN 1 ELSE 0 END                             AS obese_flag,
  CASE WHEN v.children >= 3 THEN '3+' ELSE CAST(v.children AS STRING) END AS children_band,
  CASE WHEN v.charges > b.q3 + 1.5 * (b.q3 - b.q1) THEN 1 ELSE 0 END  AS is_charges_outlier_iqr15,
  CASE WHEN v.charges > b.p99 THEN 1 ELSE 0 END                       AS is_charges_top1pct
FROM valid v CROSS JOIN bounds b;

-- COMMAND ----------

-- ---------------------------------------------------------------- motor policies (freMTPL2freq)

CREATE OR REPLACE TABLE cln_motor_policy AS
WITH typed AS (
  SELECT
    TRY_CAST(trim(IDpol) AS BIGINT)                                    AS policy_id,
    TRY_CAST(trim(ClaimNb) AS INT)                                     AS claim_nb_raw,
    TRY_CAST(trim(Exposure) AS DOUBLE)                                 AS exposure_raw,
    upper(trim(replace(Area, '''', '')))                               AS area_code,
    TRY_CAST(trim(VehPower) AS INT)                                    AS veh_power,
    TRY_CAST(trim(VehAge) AS INT)                                      AS veh_age,
    TRY_CAST(trim(DrivAge) AS INT)                                     AS driv_age,
    TRY_CAST(trim(BonusMalus) AS INT)                                  AS bonus_malus,
    upper(trim(replace(VehBrand, '''', '')))                           AS veh_brand,
    CASE WHEN lower(trim(replace(VehGas, '''', ''))) = 'diesel' THEN 'Diesel'
         WHEN lower(trim(replace(VehGas, '''', ''))) = 'regular' THEN 'Regular'
         ELSE NULL END                                                 AS veh_gas,
    TRY_CAST(trim(Density) AS DOUBLE)                                  AS density,
    upper(trim(replace(Region, '''', '')))                             AS region_code
  FROM stg_motor_policy
), dedup AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY policy_id ORDER BY exposure_raw DESC) AS rn
  FROM typed WHERE policy_id IS NOT NULL
)
SELECT
  policy_id,
  claim_nb_raw,
  LEAST(claim_nb_raw, 4)                                              AS claim_nb,
  exposure_raw,
  LEAST(exposure_raw, 1.0)                                            AS exposure,
  CASE WHEN claim_nb_raw > 4 THEN 1 ELSE 0 END                        AS is_claim_nb_capped,
  CASE WHEN exposure_raw > 1 THEN 1 ELSE 0 END                        AS is_exposure_capped,
  CASE WHEN claim_nb_raw > 0 THEN 1 ELSE 0 END                        AS has_claim,
  area_code, veh_power, veh_age, driv_age, bonus_malus, veh_brand, veh_gas,
  CAST(density AS INT)                                                AS density,
  region_code,
  CASE WHEN driv_age < 21 THEN '01: 18-20' WHEN driv_age < 26 THEN '02: 21-25' WHEN driv_age < 31 THEN '03: 26-30'
       WHEN driv_age < 41 THEN '04: 31-40' WHEN driv_age < 51 THEN '05: 41-50' WHEN driv_age < 61 THEN '06: 51-60'
       WHEN driv_age < 71 THEN '07: 61-70' ELSE '08: 71+' END         AS driver_age_band,
  CASE WHEN veh_age = 0 THEN '01: new (0)' WHEN veh_age <= 2 THEN '02: 1-2' WHEN veh_age <= 5 THEN '03: 3-5'
       WHEN veh_age <= 10 THEN '04: 6-10' WHEN veh_age <= 15 THEN '05: 11-15' ELSE '06: 16+' END AS vehicle_age_band,
  CASE WHEN bonus_malus = 50 THEN '01: 50 (max bonus)' WHEN bonus_malus <= 60 THEN '02: 51-60'
       WHEN bonus_malus <= 80 THEN '03: 61-80' WHEN bonus_malus <= 100 THEN '04: 81-100'
       ELSE '05: 101+ (malus)' END                                    AS bonus_malus_band,
  CASE WHEN veh_age > 30 THEN 1 ELSE 0 END                            AS is_veh_age_outlier,
  CASE WHEN driv_age > 90 THEN 1 ELSE 0 END                           AS is_driv_age_outlier
FROM dedup
WHERE rn = 1
  AND claim_nb_raw IS NOT NULL AND claim_nb_raw >= 0
  AND exposure_raw > 0
  AND driv_age BETWEEN 18 AND 110
  AND veh_age >= 0
  AND bonus_malus BETWEEN 50 AND 350
  AND area_code IS NOT NULL AND region_code IS NOT NULL AND veh_brand IS NOT NULL AND veh_gas IS NOT NULL;

-- COMMAND ----------

-- ---------------------------------------------------------------- motor claims (freMTPL2sev)

CREATE OR REPLACE TABLE cln_motor_claim AS
WITH typed AS (
  SELECT TRY_CAST(trim(IDpol) AS BIGINT) AS policy_id, TRY_CAST(trim(ClaimAmount) AS DOUBLE) AS claim_amount
  FROM stg_motor_claim
), valid AS (
  SELECT t.* FROM typed t
  WHERE t.policy_id IS NOT NULL AND t.claim_amount > 0
    AND t.policy_id IN (SELECT policy_id FROM cln_motor_policy)
), bounds AS (
  SELECT percentile_approx(claim_amount, 0.99) AS p99 FROM valid
)
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY v.policy_id, v.claim_amount) AS INT) AS claim_id,
  v.policy_id,
  ROUND(v.claim_amount, 2)                                            AS claim_amount,
  CASE WHEN v.claim_amount < 500 THEN '01: <500' WHEN v.claim_amount < 1000 THEN '02: 500-1k'
       WHEN v.claim_amount < 1500 THEN '03: 1k-1.5k' WHEN v.claim_amount < 5000 THEN '04: 1.5k-5k'
       WHEN v.claim_amount < 20000 THEN '05: 5k-20k' WHEN v.claim_amount < 100000 THEN '06: 20k-100k'
       ELSE '07: 100k+' END                                           AS claim_size_band,
  CASE WHEN v.claim_amount > b.p99 THEN 1 ELSE 0 END                  AS is_large_loss
FROM valid v CROSS JOIN bounds b;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schemas (Spark SQL dialect)

CREATE OR REPLACE TABLE dim_med_region AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY region) AS INT) AS med_region_key, region AS region_name
FROM (SELECT DISTINCT region FROM cln_medical) r;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_bmi_category AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY bmi_category) AS INT) AS bmi_key, bmi_category,
       CASE WHEN bmi_category LIKE '1%' THEN '< 18.5' WHEN bmi_category LIKE '2%' THEN '18.5 - 24.9'
            WHEN bmi_category LIKE '3%' THEN '25 - 29.9' ELSE '>= 30' END AS bmi_range
FROM (SELECT DISTINCT bmi_category FROM cln_medical) b;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_medical_member AS
SELECT m.member_id, r.med_region_key, b.bmi_key,
       m.age, m.age_band, m.sex, m.bmi, m.obese_flag, m.children, m.children_band,
       m.smoker_flag, m.smoker_status, m.charges, m.is_charges_outlier_iqr15, m.is_charges_top1pct
FROM cln_medical m
JOIN dim_med_region r ON m.region = r.region_name
JOIN dim_bmi_category b ON m.bmi_category = b.bmi_category;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_area AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY area_code) AS INT) AS area_key, area_code,
       CAST(MIN(density) AS INT) AS min_density, CAST(MAX(density) AS INT) AS max_density,
       CAST(percentile_approx(CAST(density AS DOUBLE), 0.5) AS INT) AS median_density
FROM cln_motor_policy GROUP BY area_code;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_fr_region AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY region_code) AS INT) AS fr_region_key, region_code
FROM (SELECT DISTINCT region_code FROM cln_motor_policy) r;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_vehicle AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY veh_brand, veh_gas, veh_power) AS INT) AS vehicle_key,
       veh_brand, veh_gas, veh_power
FROM (SELECT DISTINCT veh_brand, veh_gas, veh_power FROM cln_motor_policy) v;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_driver_age_band AS
SELECT CAST(ROW_NUMBER() OVER (ORDER BY driver_age_band) AS INT) AS driver_age_key, driver_age_band,
       MIN(driv_age) AS min_age, MAX(driv_age) AS max_age
FROM cln_motor_policy GROUP BY driver_age_band;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_motor_policy AS
SELECT p.policy_id, a.area_key, g.fr_region_key, v.vehicle_key, d.driver_age_key,
       p.claim_nb, p.claim_nb_raw, p.exposure, p.exposure_raw, p.has_claim,
       p.driv_age, p.veh_age, p.vehicle_age_band, p.bonus_malus, p.bonus_malus_band, p.density,
       COALESCE(c.claims_with_amount, 0) AS claims_with_amount,
       COALESCE(c.claim_amount_total, 0) AS claim_amount_total,
       p.is_claim_nb_capped, p.is_exposure_capped, p.is_veh_age_outlier, p.is_driv_age_outlier
FROM cln_motor_policy p
JOIN dim_area a ON p.area_code = a.area_code
JOIN dim_fr_region g ON p.region_code = g.region_code
JOIN dim_vehicle v ON p.veh_brand = v.veh_brand AND p.veh_gas = v.veh_gas AND p.veh_power = v.veh_power
JOIN dim_driver_age_band d ON p.driver_age_band = d.driver_age_band
LEFT JOIN (SELECT policy_id, COUNT(*) AS claims_with_amount, ROUND(SUM(claim_amount), 2) AS claim_amount_total
           FROM cln_motor_claim GROUP BY policy_id) c ON p.policy_id = c.policy_id;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_motor_claim AS
SELECT c.claim_id, c.policy_id, f.area_key, f.fr_region_key, f.vehicle_key, f.driver_age_key,
       c.claim_amount, c.claim_size_band, c.is_large_loss
FROM cln_motor_claim c
JOIN fact_motor_policy f ON c.policy_id = f.policy_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPI queries (Spark SQL dialect). Each result is materialised as an a_* table

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  m.members, m.avg_charges, m.median_charges, m.total_charges, m.smoker_pct,
  m.avg_charges_smoker, m.avg_charges_non_smoker,
  ROUND(m.avg_charges_smoker / m.avg_charges_non_smoker, 2)      AS smoker_loading_x,
  m.obese_pct, m.avg_bmi, m.avg_age,
  p.policies, p.exposure_years, p.claims, p.policies_with_claim_pct,
  ROUND(p.claims / p.exposure_years, 5)                           AS claim_frequency,
  c.claim_records, c.total_claim_amount, c.avg_severity, c.median_severity,
  ROUND(c.total_claim_amount / p.exposure_years, 2)               AS pure_premium,
  c.large_loss_share_pct
FROM (
  SELECT COUNT(*) AS members, ROUND(AVG(charges), 2) AS avg_charges,
         ROUND(percentile_approx(charges, 0.5), 2) AS median_charges, ROUND(SUM(charges), 2) AS total_charges,
         ROUND(100.0 * AVG(smoker_flag), 2) AS smoker_pct,
         ROUND(AVG(CASE WHEN smoker_flag = 1 THEN charges END), 2) AS avg_charges_smoker,
         ROUND(AVG(CASE WHEN smoker_flag = 0 THEN charges END), 2) AS avg_charges_non_smoker,
         ROUND(100.0 * AVG(obese_flag), 2) AS obese_pct, ROUND(AVG(bmi), 2) AS avg_bmi, ROUND(AVG(age), 2) AS avg_age
  FROM fact_medical_member) m
CROSS JOIN (
  SELECT COUNT(*) AS policies, ROUND(SUM(exposure), 2) AS exposure_years, SUM(claim_nb) AS claims,
         ROUND(100.0 * AVG(has_claim), 3) AS policies_with_claim_pct
  FROM fact_motor_policy) p
CROSS JOIN (
  SELECT COUNT(*) AS claim_records, ROUND(SUM(claim_amount), 2) AS total_claim_amount,
         ROUND(AVG(claim_amount), 2) AS avg_severity, ROUND(percentile_approx(claim_amount, 0.5), 2) AS median_severity,
         ROUND(100.0 * SUM(CASE WHEN is_large_loss = 1 THEN claim_amount ELSE 0 END) / SUM(claim_amount), 2) AS large_loss_share_pct
  FROM fact_motor_claim) c;

-- COMMAND ----------

-- Q2 Medical: smoker vs non-smoker

CREATE OR REPLACE TABLE a_med_smoker AS
SELECT smoker_status, COUNT(*) AS members, ROUND(AVG(charges), 2) AS avg_charges,
       ROUND(percentile_approx(charges, 0.5), 2) AS median_charges, ROUND(SUM(charges), 2) AS total_charges,
       ROUND(100.0 * SUM(charges) / SUM(SUM(charges)) OVER (), 2) AS share_of_total_charges_pct
FROM fact_medical_member GROUP BY smoker_status;

-- COMMAND ----------

-- Q3 Medical: age band x smoker

CREATE OR REPLACE TABLE a_med_age_smoker AS
SELECT age_band,
       COUNT(*) AS members,
       ROUND(AVG(charges), 2) AS avg_charges,
       ROUND(AVG(CASE WHEN smoker_flag = 0 THEN charges END), 2) AS avg_charges_non_smoker,
       ROUND(AVG(CASE WHEN smoker_flag = 1 THEN charges END), 2) AS avg_charges_smoker
FROM fact_medical_member GROUP BY age_band;

-- COMMAND ----------

-- Q4 Medical: BMI category x smoker (obesity interacts with smoking)

CREATE OR REPLACE TABLE a_med_bmi_smoker AS
SELECT b.bmi_category, b.bmi_range, COUNT(*) AS members,
       ROUND(AVG(f.charges), 2) AS avg_charges,
       ROUND(AVG(CASE WHEN f.smoker_flag = 0 THEN f.charges END), 2) AS avg_charges_non_smoker,
       ROUND(AVG(CASE WHEN f.smoker_flag = 1 THEN f.charges END), 2) AS avg_charges_smoker,
       SUM(f.smoker_flag) AS smokers
FROM fact_medical_member f JOIN dim_bmi_category b ON f.bmi_key = b.bmi_key
GROUP BY b.bmi_category, b.bmi_range;

-- COMMAND ----------

-- Q5 Medical: region

CREATE OR REPLACE TABLE a_med_region AS
SELECT r.region_name, COUNT(*) AS members, ROUND(AVG(f.charges), 2) AS avg_charges,
       ROUND(percentile_approx(f.charges, 0.5), 2) AS median_charges,
       ROUND(100.0 * AVG(f.smoker_flag), 2) AS smoker_pct, ROUND(AVG(f.bmi), 2) AS avg_bmi,
       ROUND(AVG(CASE WHEN f.smoker_flag = 0 THEN f.charges END), 2) AS avg_charges_non_smoker
FROM fact_medical_member f JOIN dim_med_region r ON f.med_region_key = r.med_region_key
GROUP BY r.region_name;

-- COMMAND ----------

-- Q6 Medical: children and sex

CREATE OR REPLACE TABLE a_med_children_sex AS
SELECT children_band, sex, COUNT(*) AS members, ROUND(AVG(charges), 2) AS avg_charges,
       ROUND(100.0 * AVG(smoker_flag), 2) AS smoker_pct
FROM fact_medical_member GROUP BY children_band, sex;

-- COMMAND ----------

-- Q7 Medical: driver strength (Pearson correlation with charges, and smoker-segment slope per year of age)

CREATE OR REPLACE TABLE a_med_drivers AS
SELECT 'age' AS driver, ROUND(corr(CAST(age AS DOUBLE), charges), 4) AS corr_with_charges FROM fact_medical_member
UNION ALL SELECT 'bmi', ROUND(corr(bmi, charges), 4) FROM fact_medical_member
UNION ALL SELECT 'smoker_flag', ROUND(corr(CAST(smoker_flag AS DOUBLE), charges), 4) FROM fact_medical_member
UNION ALL SELECT 'children', ROUND(corr(CAST(children AS DOUBLE), charges), 4) FROM fact_medical_member
UNION ALL SELECT 'obese_flag', ROUND(corr(CAST(obese_flag AS DOUBLE), charges), 4) FROM fact_medical_member
UNION ALL SELECT 'age (non-smokers)', ROUND(corr(CAST(age AS DOUBLE), charges), 4) FROM fact_medical_member WHERE smoker_flag = 0
UNION ALL SELECT 'bmi (smokers)', ROUND(corr(bmi, charges), 4) FROM fact_medical_member WHERE smoker_flag = 1
UNION ALL SELECT 'bmi (non-smokers)', ROUND(corr(bmi, charges), 4) FROM fact_medical_member WHERE smoker_flag = 0;

-- COMMAND ----------

-- Q8 Motor: frequency / severity / pure premium by driver age band

CREATE OR REPLACE TABLE a_motor_driver_age AS
SELECT d.driver_age_band, COUNT(*) AS policies, ROUND(SUM(f.exposure), 2) AS exposure_years,
       SUM(f.claim_nb) AS claims, ROUND(SUM(f.claim_nb) / SUM(f.exposure), 5) AS claim_frequency,
       ROUND(SUM(f.claim_amount_total) / NULLIF(SUM(f.claims_with_amount), 0), 2) AS avg_severity,
       ROUND(SUM(f.claim_amount_total) / SUM(f.exposure), 2) AS pure_premium
FROM fact_motor_policy f JOIN dim_driver_age_band d ON f.driver_age_key = d.driver_age_key
GROUP BY d.driver_age_band;

-- COMMAND ----------

-- Q9 Motor: bonus-malus band (past claims experience)

CREATE OR REPLACE TABLE a_motor_bonus_malus AS
SELECT bonus_malus_band, COUNT(*) AS policies, ROUND(SUM(exposure), 2) AS exposure_years,
       SUM(claim_nb) AS claims, ROUND(SUM(claim_nb) / SUM(exposure), 5) AS claim_frequency,
       ROUND(SUM(claim_amount_total) / NULLIF(SUM(claims_with_amount), 0), 2) AS avg_severity,
       ROUND(SUM(claim_amount_total) / SUM(exposure), 2) AS pure_premium
FROM fact_motor_policy GROUP BY bonus_malus_band;

-- COMMAND ----------

-- Q10 Motor: vehicle age band

CREATE OR REPLACE TABLE a_motor_vehicle_age AS
SELECT vehicle_age_band, COUNT(*) AS policies, ROUND(SUM(exposure), 2) AS exposure_years,
       SUM(claim_nb) AS claims, ROUND(SUM(claim_nb) / SUM(exposure), 5) AS claim_frequency,
       ROUND(SUM(claim_amount_total) / SUM(exposure), 2) AS pure_premium
FROM fact_motor_policy GROUP BY vehicle_age_band;

-- COMMAND ----------

-- Q11 Motor: area (A = rural ... F = dense urban)

CREATE OR REPLACE TABLE a_motor_area AS
SELECT a.area_code, a.median_density, COUNT(*) AS policies, ROUND(SUM(f.exposure), 2) AS exposure_years,
       SUM(f.claim_nb) AS claims, ROUND(SUM(f.claim_nb) / SUM(f.exposure), 5) AS claim_frequency,
       ROUND(SUM(f.claim_amount_total) / NULLIF(SUM(f.claims_with_amount), 0), 2) AS avg_severity,
       ROUND(SUM(f.claim_amount_total) / SUM(f.exposure), 2) AS pure_premium
FROM fact_motor_policy f JOIN dim_area a ON f.area_key = a.area_key
GROUP BY a.area_code, a.median_density;

-- COMMAND ----------

-- Q12 Motor: French region

CREATE OR REPLACE TABLE a_motor_region AS
SELECT g.region_code, COUNT(*) AS policies, ROUND(SUM(f.exposure), 2) AS exposure_years,
       SUM(f.claim_nb) AS claims, ROUND(SUM(f.claim_nb) / SUM(f.exposure), 5) AS claim_frequency,
       ROUND(SUM(f.claim_amount_total) / SUM(f.exposure), 2) AS pure_premium
FROM fact_motor_policy f JOIN dim_fr_region g ON f.fr_region_key = g.fr_region_key
GROUP BY g.region_code;

-- COMMAND ----------

-- Q13 Motor: brand x fuel

CREATE OR REPLACE TABLE a_motor_brand_gas AS
SELECT v.veh_brand, v.veh_gas, COUNT(*) AS policies, ROUND(SUM(f.exposure), 2) AS exposure_years,
       SUM(f.claim_nb) AS claims, ROUND(SUM(f.claim_nb) / SUM(f.exposure), 5) AS claim_frequency
FROM fact_motor_policy f JOIN dim_vehicle v ON f.vehicle_key = v.vehicle_key
GROUP BY v.veh_brand, v.veh_gas;

-- COMMAND ----------

-- Q14 Motor: claim-count distribution per policy (raw, before capping)

CREATE OR REPLACE TABLE a_motor_claim_count_dist AS
SELECT CASE WHEN claim_nb_raw >= 4 THEN '4+' ELSE CAST(claim_nb_raw AS STRING) END AS claims_on_policy,
       COUNT(*) AS policies, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 3) AS policies_pct
FROM fact_motor_policy
GROUP BY CASE WHEN claim_nb_raw >= 4 THEN '4+' ELSE CAST(claim_nb_raw AS STRING) END;

-- COMMAND ----------

-- Q15 Motor: severity distribution - how concentrated are losses?

CREATE OR REPLACE TABLE a_motor_severity_bands AS
SELECT claim_size_band, COUNT(*) AS claims, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS claims_pct,
       ROUND(SUM(claim_amount), 2) AS claim_amount,
       ROUND(100.0 * SUM(claim_amount) / SUM(SUM(claim_amount)) OVER (), 2) AS amount_pct
FROM fact_motor_claim GROUP BY claim_size_band;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence: before/after counts, issue counts, assertions (Spark SQL dialect)

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'medical' AS entity, (SELECT COUNT(*) FROM stg_medical) AS raw_rows,
       (SELECT COUNT(*) FROM (SELECT DISTINCT * FROM stg_medical) d) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_medical) AS clean_rows, 'all 7 columns (no natural key)' AS grain
UNION ALL SELECT 'motor_policy', (SELECT COUNT(*) FROM stg_motor_policy),
       (SELECT COUNT(DISTINCT TRY_CAST(IDpol AS BIGINT)) FROM stg_motor_policy),
       (SELECT COUNT(*) FROM cln_motor_policy), 'IDpol'
UNION ALL SELECT 'motor_claim', (SELECT COUNT(*) FROM stg_motor_claim),
       (SELECT COUNT(DISTINCT TRY_CAST(IDpol AS BIGINT)) FROM stg_motor_claim),
       (SELECT COUNT(*) FROM cln_motor_claim), 'claim row (IDpol repeats)'
UNION ALL SELECT 'fact_medical_member', NULL, NULL, (SELECT COUNT(*) FROM fact_medical_member), 'member'
UNION ALL SELECT 'fact_motor_policy', NULL, NULL, (SELECT COUNT(*) FROM fact_motor_policy), 'policy'
UNION ALL SELECT 'fact_motor_claim', NULL, NULL, (SELECT COUNT(*) FROM fact_motor_claim), 'claim'
UNION ALL SELECT 'dim_med_region', NULL, NULL, (SELECT COUNT(*) FROM dim_med_region), 'US region'
UNION ALL SELECT 'dim_bmi_category', NULL, NULL, (SELECT COUNT(*) FROM dim_bmi_category), 'WHO BMI class'
UNION ALL SELECT 'dim_area', NULL, NULL, (SELECT COUNT(*) FROM dim_area), 'area code A-F'
UNION ALL SELECT 'dim_fr_region', NULL, NULL, (SELECT COUNT(*) FROM dim_fr_region), 'French region'
UNION ALL SELECT 'dim_vehicle', NULL, NULL, (SELECT COUNT(*) FROM dim_vehicle), 'brand + fuel + power'
UNION ALL SELECT 'dim_driver_age_band', NULL, NULL, (SELECT COUNT(*) FROM dim_driver_age_band), 'driver age band';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'medical' AS entity, 'charges' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN charges IS NULL OR trim(charges) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_medical) AS raw_null_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN charges IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_medical) AS clean_null_pct,
  'required (> 0)' AS treatment
UNION ALL SELECT 'medical', 'bmi',
  (SELECT ROUND(100.0 * SUM(CASE WHEN bmi IS NULL OR trim(bmi) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_medical),
  (SELECT ROUND(100.0 * SUM(CASE WHEN bmi IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_medical), 'required (10-80)'
UNION ALL SELECT 'motor_policy', 'Exposure',
  (SELECT ROUND(100.0 * SUM(CASE WHEN Exposure IS NULL OR trim(Exposure) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_motor_policy),
  (SELECT ROUND(100.0 * SUM(CASE WHEN exposure IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_motor_policy), 'required (> 0), capped at 1'
UNION ALL SELECT 'motor_policy', 'DrivAge',
  (SELECT ROUND(100.0 * SUM(CASE WHEN DrivAge IS NULL OR trim(DrivAge) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_motor_policy),
  (SELECT ROUND(100.0 * SUM(CASE WHEN driv_age IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_motor_policy), 'required (18-110)'
UNION ALL SELECT 'motor_claim', 'ClaimAmount',
  (SELECT ROUND(100.0 * SUM(CASE WHEN ClaimAmount IS NULL OR trim(ClaimAmount) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_motor_claim),
  (SELECT ROUND(100.0 * SUM(CASE WHEN claim_amount IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_motor_claim), 'required (> 0)';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'medical: exact duplicate rows dropped' AS check_name,
       (SELECT COUNT(*) FROM stg_medical) - (SELECT COUNT(*) FROM (SELECT DISTINCT * FROM stg_medical) d) AS affected_rows
UNION ALL SELECT 'medical: rows dropped in cleaning (total)', (SELECT COUNT(*) FROM stg_medical) - (SELECT COUNT(*) FROM cln_medical)
UNION ALL SELECT 'medical: charges outlier (> Q3 + 1.5*IQR, kept)', (SELECT SUM(is_charges_outlier_iqr15) FROM cln_medical)
UNION ALL SELECT 'medical: charges top 1% (kept)', (SELECT SUM(is_charges_top1pct) FROM cln_medical)
UNION ALL SELECT 'motor_policy: duplicate IDpol', (SELECT COUNT(*) FROM stg_motor_policy) - (SELECT COUNT(DISTINCT TRY_CAST(IDpol AS BIGINT)) FROM stg_motor_policy)
UNION ALL SELECT 'motor_policy: rows dropped in cleaning (total)', (SELECT COUNT(*) FROM stg_motor_policy) - (SELECT COUNT(*) FROM cln_motor_policy)
UNION ALL SELECT 'motor_policy: Exposure > 1 year (capped at 1)', (SELECT SUM(is_exposure_capped) FROM cln_motor_policy)
UNION ALL SELECT 'motor_policy: ClaimNb > 4 (capped at 4)', (SELECT SUM(is_claim_nb_capped) FROM cln_motor_policy)
UNION ALL SELECT 'motor_policy: VehAge > 30 (flagged, kept)', (SELECT SUM(is_veh_age_outlier) FROM cln_motor_policy)
UNION ALL SELECT 'motor_policy: DrivAge > 90 (flagged, kept)', (SELECT SUM(is_driv_age_outlier) FROM cln_motor_policy)
UNION ALL SELECT 'motor_policy: ClaimNb > 0 but no severity record', (SELECT COUNT(*) FROM fact_motor_policy WHERE claim_nb_raw > 0 AND claims_with_amount = 0)
UNION ALL SELECT 'motor_policy: severity records <> ClaimNb (both > 0)', (SELECT COUNT(*) FROM fact_motor_policy WHERE claims_with_amount > 0 AND claims_with_amount <> claim_nb_raw)
UNION ALL SELECT 'motor_claim: orphan claims (IDpol not in policy file, dropped)',
       (SELECT COUNT(*) FROM stg_motor_claim WHERE TRY_CAST(IDpol AS BIGINT) NOT IN (SELECT policy_id FROM cln_motor_policy))
UNION ALL SELECT 'motor_claim: large losses (top 1%, kept)', (SELECT SUM(is_large_loss) FROM cln_motor_claim)
UNION ALL SELECT 'RI: fact_motor_policy rows lost in dim joins', (SELECT COUNT(*) FROM cln_motor_policy) - (SELECT COUNT(*) FROM fact_motor_policy)
UNION ALL SELECT 'RI: fact_medical_member rows lost in dim joins', (SELECT COUNT(*) FROM cln_medical) - (SELECT COUNT(*) FROM fact_medical_member);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_medical_member.member_id unique' AS check_name,
         (SELECT COUNT(*) - COUNT(DISTINCT member_id) FROM fact_medical_member) AS failed_rows
  UNION ALL SELECT 'fact_motor_policy.policy_id unique', (SELECT COUNT(*) - COUNT(DISTINCT policy_id) FROM fact_motor_policy)
  UNION ALL SELECT 'fact_motor_claim.claim_id unique', (SELECT COUNT(*) - COUNT(DISTINCT claim_id) FROM fact_motor_claim)
  UNION ALL SELECT 'fact_medical_member.med_region_key -> dim_med_region',
         (SELECT COUNT(*) FROM fact_medical_member WHERE med_region_key NOT IN (SELECT med_region_key FROM dim_med_region))
  UNION ALL SELECT 'fact_motor_policy.vehicle_key -> dim_vehicle',
         (SELECT COUNT(*) FROM fact_motor_policy WHERE vehicle_key NOT IN (SELECT vehicle_key FROM dim_vehicle))
  UNION ALL SELECT 'fact_motor_claim.policy_id -> fact_motor_policy',
         (SELECT COUNT(*) FROM fact_motor_claim WHERE policy_id NOT IN (SELECT policy_id FROM fact_motor_policy))
  UNION ALL SELECT 'exposure in (0, 1]', (SELECT COUNT(*) FROM fact_motor_policy WHERE exposure <= 0 OR exposure > 1)
  UNION ALL SELECT 'claim_nb in 0..4', (SELECT COUNT(*) FROM fact_motor_policy WHERE claim_nb < 0 OR claim_nb > 4)
  UNION ALL SELECT 'claim_amount > 0', (SELECT COUNT(*) FROM fact_motor_claim WHERE claim_amount <= 0)
  UNION ALL SELECT 'medical charges > 0', (SELECT COUNT(*) FROM fact_medical_member WHERE charges <= 0)
  UNION ALL SELECT 'medical smoker_flag in {0,1}', (SELECT COUNT(*) FROM fact_medical_member WHERE smoker_flag NOT IN (0, 1))
  UNION ALL SELECT 'claim amounts reconcile (fact_motor_claim = fact_motor_policy)',
         (SELECT CASE WHEN ABS((SELECT SUM(claim_amount) FROM fact_motor_claim) - (SELECT SUM(claim_amount_total) FROM fact_motor_policy)) < 1 THEN 0 ELSE 1 END)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC Run each cell, click **+ > Visualization** under the result and configure as described. The same views are pre-built in `insurance_claims_dashboard.lvdash.json`.

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Smoker vs non-smoker charges
-- Bar: X = smoker_status, Y = avg_charges
SELECT smoker_status, members, avg_charges, median_charges FROM a_med_smoker;

-- COMMAND ----------

-- Visualization: Charges by BMI x smoker
-- Grouped bar: X = bmi_category, Y = avg_charges_smoker / avg_charges_non_smoker
SELECT bmi_category, avg_charges_non_smoker, avg_charges_smoker FROM a_med_bmi_smoker ORDER BY bmi_category;

-- COMMAND ----------

-- Visualization: Charges by age band
-- Line: X = age_band, Y = avg_charges_smoker / avg_charges_non_smoker
SELECT * FROM a_med_age_smoker ORDER BY age_band;

-- COMMAND ----------

-- Visualization: Claim frequency by driver age
-- Bar: X = driver_age_band, Y = claim_frequency
SELECT * FROM a_motor_driver_age ORDER BY driver_age_band;

-- COMMAND ----------

-- Visualization: Claim frequency by bonus-malus
-- Bar: X = bonus_malus_band, Y = claim_frequency
SELECT * FROM a_motor_bonus_malus ORDER BY bonus_malus_band;

-- COMMAND ----------

-- Visualization: Claim frequency by area
-- Bar: X = area_code, Y = claim_frequency
SELECT * FROM a_motor_area ORDER BY area_code;

-- COMMAND ----------

-- Visualization: Severity concentration
-- Bar: X = claim_size_band, Y = amount_pct
SELECT * FROM a_motor_severity_bands ORDER BY claim_size_band;
