#!/usr/bin/env python3
"""Generate the Databricks SQL notebook (databricks/<name>.sql) and the Lakeview dashboard JSON from sql/02-05.
Usage: python scripts/build_databricks.py [--with-dashboard]
Project-specific settings (schema, files, visuals) live in scripts/dbx_config.py."""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from dbx_config import DBX

CATALOG, SCHEMA = "workspace", DBX["schema"]
VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/raw"
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line.split("--")[0] if ("--" in line and line[:line.find("--")].count("'") % 2 == 0) else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            out.append("\n".join(([head] if head else []) + keep).strip()); buf = []
    return out


def notebook():
    files = ", ".join(f"`{f}`" for f in DBX["files"].values())
    cells = ["-- Databricks notebook source\n" + md(f"""
# {DBX['title']} - SQL pipeline (Databricks SQL)
**Status: executed on Databricks** (serverless SQL warehouse). Generated by `scripts/build_databricks.py` from `sql/`.

1. Upload {files} to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.""")]
    cells.append(f"-- Config: change catalog / schema here (and in the dashboard JSON) if needed\nCREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging - all columns as STRING (`inferColumnTypes => false`), casting happens in 02"))
    for t, f in DBX["files"].items():
        opts = DBX.get("read_opts", {}).get(t, "format => 'csv', header => true, multiLine => true, escape => '\"', inferColumnTypes => false")
        cells.append(f"CREATE OR REPLACE TABLE {t} AS\nSELECT * EXCEPT (_rescued_data)\nFROM read_files('{VOLUME}/{f}',\n  {opts});")
    titles = {"02_cleaning.sql": "02 Cleaning", "03_model.sql": "03 Star schema", "04_analysis.sql": "04 Business KPIs",
              "05_quality_checks.sql": "05 Data-quality checks"}
    for f, title in titles.items():
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append(md("## Quality summary\nAll assertions should be PASS."))
    cells.append("SELECT * FROM dq_row_counts ORDER BY entity;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md(f"## Visualizations\nRun each cell, click **+ > Visualization** under the result and configure as described. The same views are pre-built in `{DBX['dashboard_file']}`."))
    cells.append("SELECT * FROM a_kpi_headline;")
    for title, how, q in DBX["viz"]:
        cells.append(f"-- Visualization: {title}\n-- {how}\n{q};")
    return SEP.join(cells) + "\n"


def field(n):
    return {"name": n, "expression": f"`{n}`"}


def widget(name, ds_name, fields, spec, pos):
    return {"widget": {"name": name, "queries": [{"name": "main_query", "query": {"datasetName": ds_name, "fields": fields, "disaggregated": True}}], "spec": spec}, "position": pos}


FORMATS = {
    "pct": {"type": "number-percent", "decimalPlaces": {"type": "max", "places": 2}},
    "num": {"type": "number", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 1}},
    "dec": {"type": "number", "decimalPlaces": {"type": "max", "places": 3}},
    "usd": {"type": "number-currency", "currencyCode": "USD", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 1}},
    "eur": {"type": "number-currency", "currencyCode": "EUR", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 0}},
}


def counter(name, col, title, fmt, pos):
    enc = {"fieldName": col, "displayName": title}
    if fmt: enc["format"] = FORMATS[fmt]
    return widget(name, "kpi", [field(col)], {"version": 2, "widgetType": "counter", "encodings": {"value": enc},
                                                "frame": {"showTitle": True, "title": title}}, pos)


def chart(c):
    kind, ds_name, x, y, title, pos = c["kind"], c["ds"], c["x"], c["y"], c["title"], c["pos"]
    xe = {"fieldName": x[0], "displayName": x[1], "scale": {"type": c.get("xs", "categorical")}}
    ye = {"fieldName": y[0], "displayName": y[1], "scale": {"type": "quantitative"}}
    if c.get("sort_x") == "y-reversed":
        xe["scale"]["sort"] = {"by": "y-reversed"}
    enc = {"x": ye, "y": xe} if c.get("horizontal") else {"x": xe, "y": ye}
    fields = [field(x[0]), field(y[0])]
    if c.get("color"):
        enc["color"] = {"fieldName": c["color"][0], "displayName": c["color"][1], "scale": {"type": "categorical"}}
        fields.append(field(c["color"][0]))
    return widget(c["name"], ds_name, fields, {"version": 3, "widgetType": kind, "encodings": enc,
                                              "frame": {"showTitle": True, "title": title}}, pos)


def dashboard():
    q = lambda t: f"{CATALOG}.{SCHEMA}.{t}"
    datasets = [{"name": n, "displayName": d, "queryLines": [s.format(s=f"{CATALOG}.{SCHEMA}")]} for n, d, s in DBX["datasets"]]
    pages = []
    for i, page in enumerate(DBX["pages"]):
        layout = [{"widget": {"name": f"title{i}", "multilineTextboxSpec": {"lines": [f"## {page['heading']}"]}},
                   "position": {"x": 0, "y": 0, "width": 6, "height": 1}}]
        for c in page.get("counters", []):
            layout.append(counter(*c))
        if page.get("note"):
            layout.append({"widget": {"name": f"note{i}", "multilineTextboxSpec": {"lines": [page["note"][0]]}}, "position": page["note"][1]})
        for c in page["charts"]:
            layout.append(chart(c))
        pages.append({"name": page["name"], "displayName": page["display"], "pageType": "PAGE_TYPE_CANVAS", "layout": layout})
    return {"datasets": datasets, "pages": pages}


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / DBX["notebook_file"]).write_text(notebook())
    if "--with-dashboard" in sys.argv:
        (out / DBX["dashboard_file"]).write_text(json.dumps(dashboard(), indent=1) + "\n")
    print("wrote", sorted(p.name for p in out.iterdir() if p.is_file()))
