"""Databricks settings for scripts/build_databricks.py (schema, raw files, notebook visuals, Lakeview dashboard)."""
DBX = {
    "schema": "da_learn_18",
    "title": "Insurance cost drivers & motor claim frequency",
    "notebook_file": "insurance_pipeline_notebook.sql",
    "dashboard_file": "insurance_claims_dashboard.lvdash.json",
    "dashboard_name": "da-learn-18 Insurance claims analysis",
    "files": {"stg_medical": "insurance.csv", "stg_motor_policy": "freMTPL2freq.csv", "stg_motor_claim": "freMTPL2sev.csv"},
    "viz": [
        ("Smoker vs non-smoker charges", "Bar: X = smoker_status, Y = avg_charges",
         "SELECT smoker_status, members, avg_charges, median_charges FROM a_med_smoker"),
        ("Charges by BMI x smoker", "Grouped bar: X = bmi_category, Y = avg_charges_smoker / avg_charges_non_smoker",
         "SELECT bmi_category, avg_charges_non_smoker, avg_charges_smoker FROM a_med_bmi_smoker ORDER BY bmi_category"),
        ("Charges by age band", "Line: X = age_band, Y = avg_charges_smoker / avg_charges_non_smoker",
         "SELECT * FROM a_med_age_smoker ORDER BY age_band"),
        ("Claim frequency by driver age", "Bar: X = driver_age_band, Y = claim_frequency",
         "SELECT * FROM a_motor_driver_age ORDER BY driver_age_band"),
        ("Claim frequency by bonus-malus", "Bar: X = bonus_malus_band, Y = claim_frequency",
         "SELECT * FROM a_motor_bonus_malus ORDER BY bonus_malus_band"),
        ("Claim frequency by area", "Bar: X = area_code, Y = claim_frequency",
         "SELECT * FROM a_motor_area ORDER BY area_code"),
        ("Severity concentration", "Bar: X = claim_size_band, Y = amount_pct",
         "SELECT * FROM a_motor_severity_bands ORDER BY claim_size_band"),
    ],
    "datasets": [
        ("kpi", "Headline KPIs", "SELECT members, avg_charges, smoker_loading_x, policies, claim_frequency, avg_severity FROM {s}.a_kpi_headline"),
        ("bmi", "BMI x smoker", "SELECT bmi_category, smoker_status, avg_charges FROM (SELECT bmi_category, 'smoker' AS smoker_status, avg_charges_smoker AS avg_charges FROM {s}.a_med_bmi_smoker UNION ALL SELECT bmi_category, 'non-smoker', avg_charges_non_smoker FROM {s}.a_med_bmi_smoker) ORDER BY bmi_category"),
        ("age", "Age x smoker", "SELECT age_band, smoker_status, avg_charges FROM (SELECT age_band, 'smoker' AS smoker_status, avg_charges_smoker AS avg_charges FROM {s}.a_med_age_smoker UNION ALL SELECT age_band, 'non-smoker', avg_charges_non_smoker FROM {s}.a_med_age_smoker) ORDER BY age_band"),
        ("drv", "Driver age", "SELECT driver_age_band, claim_frequency FROM {s}.a_motor_driver_age ORDER BY driver_age_band"),
        ("bm", "Bonus-malus", "SELECT bonus_malus_band, claim_frequency FROM {s}.a_motor_bonus_malus ORDER BY bonus_malus_band"),
        ("area", "Area", "SELECT area_code, claim_frequency, pure_premium FROM {s}.a_motor_area ORDER BY area_code"),
        ("sev", "Severity bands", "SELECT claim_size_band, amount_pct FROM {s}.a_motor_severity_bands ORDER BY claim_size_band"),
    ],
    "pages": [
        {"name": "medical", "display": "Medical cost drivers", "heading": "Medical insurance cost drivers (1,337 insured, full data)",
         "counters": [("kpi_avg", "avg_charges", "Avg annual charges (1,337 insured)", "usd", {"x": 0, "y": 1, "width": 2, "height": 2})],
         "note": ("Smokers average $32,050 vs $8,441 for non-smokers (3.80x). Source: Kaggle mirichoi0218/insurance. Tables: workspace.da_learn_18.", {"x": 2, "y": 1, "width": 4, "height": 2}),
         "charts": [
             {"name": "bmi_bar", "kind": "bar", "ds": "bmi", "x": ("bmi_category", "BMI category"), "y": ("avg_charges", "Avg charges"), "color": ("smoker_status", "Smoker"), "title": "Avg charges by BMI category x smoker", "pos": {"x": 0, "y": 3, "width": 3, "height": 6}},
             {"name": "age_line", "kind": "line", "ds": "age", "x": ("age_band", "Age band"), "y": ("avg_charges", "Avg charges"), "color": ("smoker_status", "Smoker"), "title": "Avg charges by age band x smoker", "pos": {"x": 3, "y": 3, "width": 3, "height": 6}}]},
        {"name": "motor", "display": "Motor claim frequency", "heading": "French motor TPL: claim frequency & severity (678,013 policies)",
         "counters": [("kpi_freq", "claim_frequency", "Claims per policy-year", "dec", {"x": 0, "y": 1, "width": 2, "height": 2})],
         "note": ("Frequency = claims (capped at 4) / exposure years (capped at 1). Avg severity EUR 2,266 per claim. Source: CASdatasets freMTPL2 via OpenML (CC0).", {"x": 2, "y": 1, "width": 4, "height": 2}),
         "charts": [
             {"name": "drv_bar", "kind": "bar", "ds": "drv", "x": ("driver_age_band", "Driver age"), "y": ("claim_frequency", "Claim frequency"), "title": "Claim frequency by driver age", "pos": {"x": 0, "y": 3, "width": 3, "height": 6}},
             {"name": "bm_bar", "kind": "bar", "ds": "bm", "x": ("bonus_malus_band", "Bonus-malus"), "y": ("claim_frequency", "Claim frequency"), "title": "Claim frequency by bonus-malus band", "pos": {"x": 3, "y": 3, "width": 3, "height": 6}},
             {"name": "area_bar", "kind": "bar", "ds": "area", "x": ("area_code", "Area (A rural - F urban)"), "y": ("claim_frequency", "Claim frequency"), "title": "Claim frequency by area density", "pos": {"x": 0, "y": 9, "width": 3, "height": 6}},
             {"name": "sev_bar", "kind": "bar", "ds": "sev", "x": ("claim_size_band", "Claim size"), "y": ("amount_pct", "% of claim EUR"), "title": "Share of claim EUR by claim size", "pos": {"x": 3, "y": 9, "width": 3, "height": 6}}]},
    ],
}
